# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LifeManagementApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LifeManagementApp
    pod 'Firebase/Core'
    pod 'Firebase/Database'
    pod 'Firebase/Storage'
    pod 'Firebase/Auth'
    pod 'KDCircularProgress'

  target 'LifeManagementAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LifeManagementAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
